export const siteText = {


  title: "To The Most Beautiful Person In The World ❤️",
  subtitle: "Thae Thu",
  buttonLabel: "Start",
  footerText: "Made with Next.js",
  buttonOne: "Click Here 💞",
  buttonTwo: "Back To Flowers",
  buttonThree: "Ride",
  moonText: "You are like a moon, so pretty & so tiny",
  question: `mote srr chin lo website pr yay lite p xD
  mote wal kah py pr lr
   ya lr ma thi woo (づ •. •)?`,
  agreeText: "ya pr tl :0",
  disagreeText: "ma ya buu",
  questionOne: "br pyit a sin pyay pr tl nw",
  questionTwo: "ummm, candy lout so ll a sin pyay hmr pr, ak ll ma ya buu lr?",
  questionThree: "a ti gyi ma wal kywy phuu pop",
  questionFour: "aww ma ya pr buu, gone sin hmr pl",
  questionFive: "ak lo nww thae thu, chee htoke pl",
  questionSix: "mote srr chin tl kid ly pr",
  questionSeven: "grrrrr ma ya buu pl nhate tok hmr lr",
  questionEight: "a chin chin twy ko nww, sy ta nrr ma shi buu pop",
  questionNine: "hrr lote pyn p, zoot nyin nrr pl",
  questionTen: "brr lo ll loh, br lo ll loh, friend twy so",
  questionEleven: "wahaha, bl pyay ma ll kwa, ma ya lo ma ya tok buu ly",
  asteroidTextTopRight: "is that T3??? who is that? \n ahh I miss my T3",
  asteroidTextLeft: "It's crazy, but it's true\nThere's nothing I won't do\nI'd risk it all for you\n- Bruno Mars",
  asteroidTextRight: "just wanna make you\nhappiest person in the world\ncuz ur existance\n alone makes me happy",
  countdownTitle: "Oh Asteriod is blocking our way..., let's bomb it🤔",
  countdownReady: "A Black Hole??? ✨",
  countdownButton: "Let's Goooo !",
  formQuestion: "Haha Gotcha!!!, btw when will you come back? ( ╹ -╹)?",
  formOne: "Date",
  formTwo: "Time",
  receiverEmail: "winyumg2003a@gmail.com",
  blackholeEnter: "Enter",
  blackholeTooSmall: "blackhole is too small, pick and drop rocks to throw into it",
  blackholeReady: "blackhole is ready, enter it",
  multiverseLabel: "Every version of me would give the whole multiverse just to have you in my daily life 🌠"
};