export const siteText = {


  title: "To The Most Beautiful Person In The World ❤️",
  subtitle: "Thae Thu",
  buttonLabel: "Start",
  footerText: "Made with Next.js",
  buttonOne: "Click Here 💞",
  buttonTwo: "Back To Flowers",
  buttonThree: "Click Here",
  moonText: "You are like a moon, so pretty & so tiny",
  question: "nyima pyn lr yin lr kyo ml nww, could you please let me ???",
  agreeText: "ya",
  disagreeText: "ma ya",
  questionOne: "1",
  questionTwo: "2",
  questionThree: "3",
  questionFour: "4",
  questionFive: "5",
  questionSix: "6",
  questionSeven: "7",
  questionEight: "8",
  questionNine: "9",
  questionTen: "10",
  questionEleven: "11",
  formQuestion: "Flight Time lay please",
  formOne: "Date",
  formTwo: "Time",
  receiverEmail: "winyumg2003a@gmail.com"
};